### ISSUE TITLE
Mt4 v2.06 version has import dll problem！

### ISSUE THREAD

**Issue by shawnxiaos** [TheSnowGuru/PyTrader-python-mt4-mt5-trading-api-connector-drag-n-drop#12]
I had set allow import dll ，but it still tell me Alert: Allow DLL import ；
Did I set something wrong？

![image](https://user-images.githubusercontent.com/33209880/115829766-f1b60700-a441-11eb-9a2c-6670c1d9dbdd.png)

![image](https://user-images.githubusercontent.com/33209880/115829814-01cde680-a442-11eb-99dd-85fd5098f9d0.png)

2021.04.23 14:40:48.417	Expert Pytrader_MT4_EA_V2.06 CADJPY+,H1: removed
2021.04.23 14:40:48.413	Pytrader_MT4_EA_V2.06 CADJPY+,H1: Server socket terminated
2021.04.23 14:40:48.413	Pytrader_MT4_EA_V2.06 CADJPY+,H1: uninit reason 8
2021.04.23 14:40:48.413	Pytrader_MT4_EA_V2.06 CADJPY+,H1: initialization failed (1)
2021.04.23 14:40:48.413	Pytrader_MT4_EA_V2.06 CADJPY+,H1: Alert: Allow DLL import. 
2021.04.23 14:40:48.348	Pytrader_MT4_EA_V2.06 CADJPY+,H1 inputs: ServerPort=1122; location=Market\Pytrader mt4 Python; 
2021.04.23 14:40:09.424	Expert Pytrader_MT4_EA_V2.06 CADJPY+,H1: loaded successfully

My OS Version：
![image](https://user-images.githubusercontent.com/33209880/115830073-612bf680-a442-11eb-8b13-c7e3f234e273.png)
My Mt4 platform：
![image](https://user-images.githubusercontent.com/33209880/115830189-86206980-a442-11eb-9a92-acb90d7e3c71.png)

**Comment by shawnxiaos** [comment]
I had set autotrading too.
![image](https://user-images.githubusercontent.com/33209880/115831189-d51ace80-a443-11eb-8395-7a62facceaa2.png)

**Comment by Branly76** [comment]
So problem solved ???

**Comment by cevangelio** [comment]
This happened to me too and even if you tick Allow DLL import, it keeps giving the message. The solution is to permanently tick Allow DLL import from Tools > Options > Expert Advisors
