### ISSUE TITLE
Method Copy_rates_from issue

### ISSUE THREAD

**Issue by araujocaio** [TheSnowGuru/PyTrader-python-mt4-mt5-trading-api-connector-drag-n-drop#14]
Hi there, 

I would like to report an issue with a method. 

I have used successfully run the following code with ticks: 

	# request 1000 ticks from EURAUD
	euraud_ticks = mt5.copy_ticks_from("EURAUD", datetime(2020,1,28,13), 1000, mt5.COPY_TICKS_ALL)
	# request ticks from AUDUSD within 2019.04.01 13:00 - 2019.04.02 13:00
	audusd_ticks = mt5.copy_ticks_range("AUDUSD", datetime(2020,1,27,13), datetime(2020,1,28,13), mt5.COPY_TICKS_ALL)
	 
But when I use this for : 

	eurusd_rates = mt5.copy_rates_from("EURUSD", mt5.TIMEFRAME_H1, datetime(2020,1,28,13), 1000)

The same way is explained here: 

https://www.mql5.com/en/docs/integration/python_metatrader5/mt5copyratesfrom_py

No matter what period, symbol, or timeframe, the object It returns is always "None" (not null). 

Are you experiencing the same issue? 

Thanks in advance

**Comment by Branly76** [comment]
@araujocaio

Hi,
You are using the API from MQL. This one I do not use.
So I do not have this experience.

Or is the question if the same problem is with this API ?

BR
