### ISSUE TITLE
Getting EA working on Demo message after upgrade to 2.06a

### ISSUE THREAD

**Issue by cevangelio** [TheSnowGuru/PyTrader-python-mt4-mt5-trading-api-connector-drag-n-drop#16]
![PyTrader issue 2 06a](https://user-images.githubusercontent.com/10350455/119958931-1455b580-bfd6-11eb-8b48-9ca24eaa6e3b.png)
Hi, 

Not sure why but I suddenly get the message that my PyTrader is on demo only. I am logged in MQL and still have the indicator. What could be the issue?

**Comment by Branly76** [comment]
Hi,

Crosscheck.
If you go back to 2.06 then you have licensed again ?

BR

**Comment by cevangelio** [comment]
Hi, deleting the indicator and redownloading made it work again but it removed 1 activation from the account. I got this message "You have activated the product "Pytrader mt4 Python" https://www.mql5.com/en/market/product/58254, 3 of 5 activations left. (See Rules, IV.10 and IV.11 https://www.mql5.com/en/market/rules )"

This is not very fair. I am using same exact computer and MT4.

**Comment by Branly76** [comment]
Hi,

I do not understand why this happens.
Let us see if other users have same problem.

BR
