### ISSUE TITLE
Open order issue

### ISSUE THREAD

**Issue by mrb0098** [TheSnowGuru/PyTrader-python-mt4-mt5-trading-api-connector-drag-n-drop#19]
I get this error when I try to open a new order using the library demo version:
order_error : 0
order_return_message : Trading not allowed

**Comment by Branly76** [comment]
Which instrument are you using. In demo the API is working for 5 instruments.
"EURUSD", "AUDCHF", "NZDCHF", "GBPNZD", "USDCAD"
