### ISSUE TITLE
can i get the indicators data from this api?

### ISSUE THREAD

**Issue by majiddjango** [TheSnowGuru/PyTrader-python-mt4-mt5-trading-api-connector-drag-n-drop#2]
hi there! 
great job i wanted to know that can i get indicator data from this api?

**Comment by Branly76** [comment]
Custom indicator data or buildin indicaror data ?

BR

**Comment by majiddjango** [comment]
> Custom indicator data or buildin indicaror data ?
> 
> BR

custom indicators

**Comment by badgeek** [comment]
is this free?

**Comment by Branly76** [comment]
Is free for the following instruments  EURUSD, AUDCHF, NZDCHF, GBPNZD and USDCAD.
All function are working for unlimited time.

**Comment by Branly76** [comment]
Done
