### ISSUE TITLE
setting trailing stop

### ISSUE THREAD

**Issue by bhralzz** [TheSnowGuru/PyTrader-python-mt4-mt5-trading-api-connector-drag-n-drop#22]
Hi,
is it possible to set trailing stop while sending order via mt5?
if no, is there another mechanism doing that automatically using Metatrader itself?
thanks

**Comment by Branly76** [comment]
Hi,

You can set the SL as a trailing, but it means you have to regularly retrieve the open positions and check distance market price and SL.

This is the way you can do. But it needs some code. I think I have somewhere the code for this.

But there is now not an auto trailing stop.
I'm not sure if it will be possible to do this by code, only once.
I will check if possible.

BR

**Comment by bhralzz** [comment]
Thanks for your kindly reply,
waiting to hear from you.

**Comment by bhralzz** [comment]
> Hi,
> 
> You can set the SL as a trailing, but it means you have to regularly retrieve the open positions and check distance market price and SL.
> 
> This is the way you can do. But it needs some code. I think I have somewhere the code for this.
> 
> But there is now not an auto trailing stop. I'm not sure if it will be possible to do this by code, only once. I will check if possible.
> 
> BR

Did you checked that? trailing stop code?
