### ISSUE TITLE
Couldnt connect with the socket-server

### ISSUE THREAD

**Issue by l736k** [TheSnowGuru/PyTrader-python-mt4-mt5-trading-api-connector-drag-n-drop#24]
Hi,
I get the following order when trying to open a connection:
Couldnt connect with the socket-server: [WinError 10061] No connection could be made because the target machine actively refused itelf.sock

I tryed different ports without success. The EA is attached to the chart because if a right click on it i see Pytrader context menù but I don't see icons over the chart (I used to see the EA version with the smile in the upper right corner and the licensed info with the port number in the upper left corner).

**Comment by Branly76** [comment]
If OK, contact me by discord.
To find out what the problem is, will be more easy in an interactive way.

BR
Huub

**Comment by l736k** [comment]
Hi, sorry but I don't use Discord...I've just followed you on Twitter, you can DM me there. Thanks

**Comment by l736k** [comment]
Hi, could you please help me to solve the problem?
