### ISSUE TITLE
How can I connect my demo account

### ISSUE THREAD

**Issue by Near-Tam** [TheSnowGuru/PyTrader-python-mt4-mt5-trading-api-connector-drag-n-drop#25]
I found that there is no server ip in my demo account. How can I connect my demo account base on this situation.

**Comment by Branly76** [comment]
Hi,

Not exactly clear what you mean. You move the MT4/MT5 EA into a chart. On the upper right side of the chart you will have a happy face and on the upper left side demo or licensed. On this machine/pc the IP address will be 127.0.0.1. If your python script is on the same machine/pc then use 127.0.0.1 as IP and the socket number as seen in the MT ea in the connect function.

If not clear, lets chat by the discord channel.


BR
Huub

**Comment by Near-Tam** [comment]
when I was ran the Python_script_example_PyTrader.py file
it return an error:
Couldnt connect with the socket-server: [Errno 61] Connection refusedelf.sock
 terminating program
False
Traceback (most recent call last):
  File "Python_script_example_PyTrader.py", line 95, in <module>
    CheckAlive = MT.Check_connection()
  File "/Users/neablister/PycharmProjects/PyTrader-python-mt4-mt5-trading-api-connector-drag-n-drop/Pytrader_API_V2_08.py", line 208, in Check_connection
    ok, dataString = self.send_command(self.command)
  File "/Users/neablister/PycharmProjects/PyTrader-python-mt4-mt5-trading-api-connector-drag-n-drop/Pytrader_API_V2_08.py", line 1825, in send_command
    self.sock.send(bytes(self.command, "utf-8"))
BrokenPipeError: [Errno 32] Broken pipe

How can I fix it ?

**Comment by Branly76** [comment]
Do you have the MT4/% EA running in a metatrader terminal.
Licensed or demo does not matter.

![afbeelding](https://user-images.githubusercontent.com/64263524/168806349-982c7e08-ba2a-4215-89a7-cd73bc982aef.png)

**Comment by Near-Tam** [comment]
like this?
<img width="1074" alt="image" src="https://user-images.githubusercontent.com/23352749/168808037-067c47f1-deb8-45b6-bfa7-5e563b7ac218.png">

**Comment by Branly76** [comment]
You need to have the MT4/5 EA in only one chart.
![afbeelding](https://user-images.githubusercontent.com/64263524/168808621-52172a17-a2dd-4d57-a1d8-073511ac1977.png)

Watch the red arrows, do you have the info above in your chart.

BR

**Comment by Branly76** [comment]
I wrote a lot of documentation, did you read this .pdf.   ???
BR

**Comment by Near-Tam** [comment]
Thx, I'll read it now.

**Comment by Branly76** [comment]
You can also contact me on discord, chatting is much easier.
BR
