### ISSUE TITLE
Unable to get the data of us100cash

### ISSUE THREAD

**Issue by Hoogck** [TheSnowGuru/PyTrader-python-mt4-mt5-trading-api-connector-drag-n-drop#26]
Why is it limited to (EURUSD, AUDCHF, NZDCHF, GBPNZD and USDCAD) these instruments? How can they be modified to adapt to more?

**Comment by Branly76** [comment]
Hi,

It is a commercial product. The above mentioned instruments are free in full functions. This is done for eveluating the product.

Best regards
Huub
