### ISSUE TITLE
Python Strategy Script Error: No connection could be made because the target machine actively refused itelf.sock

### ISSUE THREAD

**Issue by BaseMax** [TheSnowGuru/PyTrader-python-mt4-mt5-trading-api-connector-drag-n-drop#32]
```
C:\Users\Max\PyTrader-python-mt4-mt5-trading-api-connector-drag-n-drop\Strategies>python ma_cross_strategy.py
Start MT
Next...
Couldnt connect with the socket-server: [WinError 10061] No connection could be made because the target machine actively refused itelf.sock
 terminating program

C:\Users\Max\PyTrader-python-mt4-mt5-trading-api-connector-drag-n-drop\Strategies>python ma_cross_strategy.py
Start MT
Next...
Couldnt connect with the socket-server: [WinError 10061] No connection could be made because the target machine actively refused itelf.sock
 terminating program

C:\Users\Max\PyTrader-python-mt4-mt5-trading-api-connector-drag-n-drop\Strategies>python ma_cross_strategy.py
Start MT
Next...
Couldnt connect with the socket-server: [Errno 11001] getaddrinfo failedelf.sock
 terminating program

C:\Users\Max\PyTrader-python-mt4-mt5-trading-api-connector-drag-n-drop\Strategies>python ma_cross_strategy.py
Start MT
Next...
Couldnt connect with the socket-server: [WinError 10061] No connection could be made because the target machine actively refused itelf.sock
 terminating program
```

Source code:
```
# settings
timeframe = 'M1'
instrument = 'EURUSD'
# server_IP = '127.0.0.1'
# server_IP = 'locahost'
server_IP = '192.168.1.1'
server_port = 1122                                              # check port number
...
```

![image](https://user-images.githubusercontent.com/2658040/214400784-20e3fbdc-1498-4fe3-ae45-c049ccda4c6f.png)

Experts setting:
![image](https://user-images.githubusercontent.com/2658040/214400822-a4f5664e-5624-4120-a1b5-363fb7fa4cb7.png)

**Comment by Branly76** [comment]
Hi,

Normally I use 127.0.0.1 

![afbeelding](https://user-images.githubusercontent.com/64263524/214668770-eda78eda-e9d6-4784-a0b4-86e0283dafcb.png)


BR

**Comment by BaseMax** [comment]
> Hi,
> 
> Normally I use 127.0.0.1
> 
> ![afbeelding](https://user-images.githubusercontent.com/64263524/214668770-eda78eda-e9d6-4784-a0b4-86e0283dafcb.png)
> 
> BR

Thank you so much for your answer.

- What auth code should we use in the EA setting? (demo version)

- And would you explain more about "Folder and name indicator"? I don't know what I must setup for that and what is Market directory.

**Comment by Branly76** [comment]
Autorization code was a request from some users as extra safety. If you fill in a code and do the same for the pytrader_API then the authorization codes are compared. Default it is None, which is also already a check. This is for upwards compatibility.
So for default you have to do nothing.

If you did buy a license, the above indicator is installed in the Market folder. The EA checks if this indicator is available and checks several values within this indicator. Then the EA will be licensed, if the indicator can not be found, then it will be demo.

**Comment by IntellaCoder** [comment]
In order to get a license, how much should I pay and where can I find out the license?

**Comment by Branly76** [comment]
https://www.mql5.com/en/market/product/58243#
