### ISSUE TITLE
issue with license 

### ISSUE THREAD

**Issue by Sedik7** [TheSnowGuru/PyTrader-python-mt4-mt5-trading-api-connector-drag-n-drop#49]
Hello Sir 
email :  sedikbakhtaoui@yahoo.com

i try the Pytrader demo was very good and fast and then i bought license Order number 230928_**96 today and MT4 install Pytrader mt4 Python 2.06 as indicator not EA, there is no place to input the Authorization code and cannot connect with it same socket port 1110
so in conclusion the installed indicator Pytrader mt4 Python 2.06 is not working at all ,  no place to put Authorization code and couldn't connect with 

also another question mentioned 5 activation based on machine or MT4 account if so (include demo MT4 account?)

your feed back is highly appreciated

**Comment by Sedik7** [comment]
sorry the lost connection in demo due to the mistypo of the port number so connected again in demo but i confirm to you never success to connect with indicator Python 2.06 as indicator  or found where to put the Authorization code

**Comment by Branly76** [comment]
Hi,
Yep late reaction.
If you buy the license an indicator for the authorization will be installed. This is done in s special folder under the indicators folder of your MT4/5 terminal.
Next you download and move the latest EA into the experts folder of MT4/5. We are now at version 3.02.
This EA you move into a chart and you will see it will work. If still not ok, please let us have conversation at discord under support. It is there easier to show some pictures.
Best regards,
Branly

**Comment by Sedik7** [comment]
Dear sir 
many thanks for your replay, guidance, now is working perfectly i test it on all instruments, i request last ticks, instrument info, last 4 bars because it is week end i cannot open and close but it is working , the issue was the MQL5 install the indicator in another MT4 where there was not the EA just put them in same MT4 it is working, later i will delete this issue think you and have nice week end

**Comment by Sedik7** [comment]
Subject: PyTrader API Implementation Feedback and Technical Issues
Dear Sir , hope this email found you well

I hope this email finds you well. I am writing to provide feedback and report several persistent issues encountered while implementing your PyTrader API for MT4/MT5 connectivity. We've been working on a Forex data collection system, and I wanted to share our findings to help improve the API.

Key Issues Encountered:

1. Data Format Inconsistencies
   - The `Get_last_x_bars_from_now()` method sometimes returns string-formatted data instead of the expected list format
   - Inconsistent delimiter usage in string responses (using '$' separator)
   - No clear documentation on how to parse these different response formats

2. Method Availability and Documentation
   - The `Get_last_tick_info()` method appears in documentation but doesn't exist in the API
   - Some methods like `Symbol_select_tick()` have unclear return value specifications
   - Missing documentation about error codes and their meanings

3. Connection Management
   - Intermittent connection drops without clear error messages
   - Socket errors not providing sufficient detail for debugging
   - No automatic reconnection mechanism in case of connection loss

4. Error Handling
   - The `socket_error` and `command_return_error` states sometimes remain set even after successful operations
   - Timeout values are not consistently respected
   - Error messages don't always correspond to the actual issue

Suggested Improvements:

1. Data Handling
   - Standardize return formats across all methods
   - Provide clear documentation on data structure and parsing
   - Add helper methods for common data format conversions

2. Documentation
   - Update method documentation to match actual implementation
   - Add comprehensive error code reference
   - Include more usage examples, especially for error handling

3. Connection Management
   - Implement automatic reconnection mechanism
   - Add detailed connection state reporting
   - Provide connection health check method

4. Error Handling
   - Reset error states after each operation
   - Implement more detailed error reporting
   - Add method-specific error codes

We have implemented various workarounds for these issues, but addressing them at the API level would greatly improve the user experience. I would be happy to provide more detailed information or test cases if needed.

Current Workarounds Implemented:
```python
# Example of our current workaround for data format inconsistency
def parse_rates(raw_response):
    if isinstance(raw_response, str):
        # Handle string format with $ delimiter
        return [tuple(map(float, row.split('$'))) for row in raw_response.split(';')]
    return raw_response  # Assume list format
```

Would you be interested in our complete test suite that demonstrates these issues? We'd be happy to contribute to improving the API's reliability and usability.

Thank you for your time and consideration.

Best Regards
Sedik
________________________________
