### ISSUE TITLE
MT4 Unhandled exception 0xE0434352, Pytrader_MT4_EA_V1.02 EURUSD,M1: not initialized, Pytrader_MT4_EA_V1.02 EURUSD,M1: uninit reason 8

### ISSUE THREAD

**Issue by drbothen** [TheSnowGuru/PyTrader-python-mt4-mt5-trading-api-connector-drag-n-drop#6]
Everytime i try to add the ea to the chart i receive the following

2020.11.20 12:29:05.318	Expert Pytrader_MT4_EA_V1.02 EURUSD,M1: removed
2020.11.20 12:29:05.318	Pytrader_MT4_EA_V1.02 EURUSD,M1: uninit reason 8
2020.11.20 12:29:05.318	Pytrader_MT4_EA_V1.02 EURUSD,M1: not initialized
2020.11.20 12:29:05.318	Unhandled exception 0xE0434352
2020.11.20 12:29:04.646	Pytrader_MT4_EA_V1.02 EURUSD,M1: Server socket created
2020.11.20 12:29:04.474	Pytrader_MT4_EA_V1.02 EURUSD,M1 inputs: ServerPort=22222; key=; activation_key=; 
2020.11.20 12:28:59.162	Expert Pytrader_MT4_EA_V1.02 EURUSD,M1: loaded successfully

I have add .net 3.5 as well as installed  Microsoft Visual C++ Redistributable for Visual Studio 2015, 2017 and 2019. I am running this on server 2019, what am I missing?

thanks!

**Comment by Branly76** [comment]
Hi,

With MT4 had some problems, due to unmanaged code.
Give me this weekend to check all and give you an update.
Sorry for the inconveniences

**Comment by Branly76** [comment]
Uploaded a new version 1.04.
This one should work, anyway here is working.
If still problems, contact me by huub.emonts@gmail.com

BR
