### ISSUE TITLE
Limitation for get all closed positions

### ISSUE THREAD

**Issue by brenoperucchi** [TheSnowGuru/PyTrader-python-mt4-mt5-trading-api-connector-drag-n-drop#7]
Has some limitations about the number of information you could request?

I only get 14 most recent pieces of information but have more than 30 records.

```python 
(Pdb) timezone = pytz.timezone("Etc/UTC")
(Pdb) self.connect().Get_all_closed_positions(date_from=datetime(2020, 3, 3, tzinfo=timezone), date_to=datetime.now())

    position_ticket instrument  order_ticket position_type  magic_number  volume  open_price   open_time  close_price    close_time        comment  profit  swap  commission
0         832580774     EURUSD     832580946          sell          2000    0.03     1.20699  1610953450      1.20700  1.610953e+09  Perucchi Inc    -0.03   0.0         0.0
1         832580780     EURUSD     832580986          sell          2000    0.02     1.20699  1610953451      1.20700  1.610953e+09  Perucchi Inc    -0.02   0.0         0.0
2         832580815     EURUSD     832581007          sell          2000    0.03     1.20699  1610953453      1.20700  1.610953e+09  Perucchi Inc    -0.03   0.0         0.0
3         832580820     EURUSD     832581032          sell          2000    0.02     1.20699  1610953453      1.20700  1.610953e+09  Perucchi Inc    -0.02   0.0         0.0
4         832580854     EURUSD     832581072          sell          2000    0.03     1.20699  1610953456      1.20700  1.610953e+09  Perucchi Inc    -0.03   0.0         0.0
5         832580860     EURUSD     832581075          sell          2000    0.02     1.20699  1610953456      1.20696  1.610953e+09  Perucchi Inc     0.06   0.0         0.0
6         832583189     EURUSD     832596730          sell          2000    0.03     1.20680  1610953645      1.20682  1.610955e+09  Perucchi Inc    -0.06   0.0         0.0
7         832583195     EURUSD     832596740          sell          2000    0.02     1.20680  1610953645      1.20683  1.610955e+09  Perucchi Inc    -0.06   0.0         0.0
8         832585809     EURUSD     832596763          sell          2000    0.03     1.20690  1610953838      1.20685  1.610955e+09  Perucchi Inc     0.15   0.0         0.0
9         832594901     EURUSD     832596781          sell          2000    0.03     1.20659  1610954452      1.20685  1.610955e+09  Perucchi Inc    -0.78   0.0         0.0
10        832595835     EURUSD     832596799          sell          2000    0.03     1.20673  1610954498      1.20685  1.610955e+09  Perucchi Inc    -0.36   0.0         0.0
11        832597571     EURUSD     833245634          sell          2000    0.02     1.20673  1610954609      1.20592  1.610983e+09  Perucchi Inc     1.62   0.0         0.0
12        832597566     EURUSD     833245647          sell          2000    0.03     1.20673  1610954608      1.20592  1.610983e+09  Perucchi Inc     2.43   0.0         0.0
13        833654586     EURUSD     833658133          sell          2000    0.03     1.20739  1611001925      1.20742  1.611002e+09  Perucchi Inc    -0.09   0.0         0.0
14        833654590     EURUSD     833658137          sell          2000    0.02     1.20739  1611001926      1.20742  1.611002e+09  Perucchi Inc    -0.06   0.0         0.0`
```
Suggest:
- get information MetaTrader history by ticket (even open or closed)

**Comment by Branly76** [comment]
Will check this, is it MT4 or MT5 ?
BR

**Comment by brenoperucchi** [comment]
> Will check this, is it MT4 or MT5 ?
> For MT4 you can only retrieve the closed trades available in the MT4 terminal. As you know you can set the history of closed orders starting from day and so on. If in the terminal history you see only 12 closed orders, the python api can give back only this 12 closed orders, independent of your start date in the call,
> 
> BR

MT5_EA_V2.02

**Comment by Branly76** [comment]
I did i try to, got the next return.
![afbeelding](https://user-images.githubusercontent.com/64263524/105037962-06f45180-5a5f-11eb-8e6f-02066c717f7e.png)

Used the following code

timezone = pytz.timezone("Etc/UTC")
AllClosedPositions = MT.Get_all_closed_positions(
    date_from=datetime(2021, 1, 1, tzinfo=timezone), date_to=datetime.now())

Anyway i will do some more testing.

BR

**Comment by Branly76** [comment]
Hi,

The date comparision with now has an item. From to is it including this day or not. I will adapt this and make an update.

BR

**Comment by Branly76** [comment]
Hi,

If your broker has a difference in time with your local time, this can happen. I tested on ICM broker and had the same problem.

timezone = pytz.timezone("Etc/UTC")
AllClosedPositions = MT.Get_all_closed_positions(
    date_from=datetime(2021, 1, 1, tzinfo=timezone), date_to=datetime.now() + timedelta(hours=1))

For this broker just added 1 hour to local time

BR

**Comment by brenoperucchi** [comment]
I was thinking about server time too but your solution or mine doesn't solved the problem. Maybe the server is delaying the information about history? For testing, I will change my broker to the ICM.

I just closed the trade operation in a new demo account on MetaTrader 5 and after that, I try to get all closed positions from the API and I received nothing.

```python
meta.Get_all_closed_positions(date_from=datetime(2020, 1, 19, 0, tzinfo=timezone),date_to=datetime.now())
```

![Screen Shot 2021-01-19 at 17 50 35](https://user-images.githubusercontent.com/367967/105091606-d9b79b80-5a7e-11eb-8412-8443943b6c0b.png)

I closed the trade operation in the new demo account on meta trader 5 and I send the command to get the closed position and now get the operation.

```python
(Pdb) meta.Get_all_closed_positions(date_from=datetime(2021, 1, 1, tzinfo=timezone), date_to=datetime.now() + timedelta(hours=1))
Empty DataFrame
Columns: [position_ticket, instrument, order_ticket, position_type, magic_number, volume, open_price, open_time, close_price, close_time, comment, profit, swap, commission]
Index: []
(Pdb)
```

ps: I woke up this morning with yesterday's results from 14 records changed to 40 without changing anything in the code.

**Comment by Branly76** [comment]
Hi,

Which broker are you using.
Then i can try also

BR

**Comment by brenoperucchi** [comment]
I'm using ActivTrades 
https://www.activtrades.com/

**Comment by Branly76** [comment]
Hi,

This can be the case depending on time difference between broker server time, which are the open/close times and your local time.
I did a test with 20 trades and closed them directly.
I was missing them all in the call.
I went out for a while and tried again and yes they were there.
Then i tried again and all not there.
Then i changed/added the extra hour, and all where there again.

Will see if i can try with your broker too.

BR

**Comment by brenoperucchi** [comment]
You was right! 

My time zone is 3 ahead of UTC but the server was 5 hours from me. When trying your suggested but change to 3 hours and not verify the date-time of server information.
```python 
(date_from=datetime(2021, 1, 1, tzinfo=timezone), date_to=datetime.now() + timedelta(hours=3))
```
![image](https://user-images.githubusercontent.com/367967/105103982-38394580-5a90-11eb-9d53-93f0c73f18ef.png)

Sorry for this issue!

**Comment by brenoperucchi** [comment]
![image](https://user-images.githubusercontent.com/367967/105104733-9e729800-5a91-11eb-856c-9647fd29d596.png)

But one record was left out

![image](https://user-images.githubusercontent.com/367967/105104860-d11c9080-5a91-11eb-984c-d824d5d5d73d.png)

**Comment by Branly76** [comment]
HI,

Yep i know why.
Iteration one to short. I changed already, will upload new version later.

BR

**Comment by Branly76** [comment]
Version 2.03 is available

BR
