### ISSUE TITLE
How much I need to pay for use this service

### ISSUE THREAD

**Issue by moon-web28** [TheSnowGuru/PyTrader-python-mt4-mt5-trading-api-connector-drag-n-drop#8]
I want to use your service, I just want to get All Closed Positions from MT4 for multiple accounts
so can you tell me how I will do this and how much I need to pay?

**Comment by TheSnowGuru** [comment]
https://www.mql5.com/en/market/product/58254?source=Site+Profile

**Comment by moon-web28** [comment]
I have read this but still, I have those questions
1. Will it be free or paid only?
2. can use more than one MT4 account?

**Comment by TheSnowGuru** [comment]
You can use unlimited amount of metatrader as long as its on the same VPS. and up to 5 different VPS.

Its has a small fee on mql marketplace.

 

Good luck

**Comment by Branly76** [comment]
For every account you have, a MT4 terminal must be running. The EA must be in 1 chart of every MT4 terminal. For every MT4 terminal the EA must have a different portnumber. By connecting in python you can connect to a terminal and retrieve the historical orders. So connect, retrieve and disconnect. Other way is that you have multiple instances of the Pytrader_API. Just what you like. For MT4 the amount of historical orders is determined by the history in the MT4 terminal. But this is also the same for mql4 coding.

**Comment by Branly76** [comment]
@moon-web28

For 5 instruments the EA is working in full functionality.
Read the documentation.
BR
