### ISSUE TITLE
Demo mode - port not being opened for connection from python script MT4

### ISSUE THREAD

**Issue by marcusjfloyd** [TheSnowGuru/PyTrader-python-mt4-mt5-trading-api-connector-drag-n-drop#9]
Hey everyone,

I'm testing before I buy. In the demo, I'm testing with port 1122. I've disabled my firewalls and av software and it doesn't look like port 1122 is being opened for me to connect to. I've tried other ports as well. Am I missing something?

I've tried with both MT4 EA versions 2.03 and 2.05 and made sure the dll imports are allowed

**Comment by Branly76** [comment]
Hi, 

The port number cann't be the problem. I also use AV software for protecton. Had nothing to change at all.
Do you get an error message if you try to connect ?

BR

**Comment by marcusjfloyd** [comment]
Eh, I just used a larger port number and that worked for me. I changed it to 65000. I'm ok with that.

**Comment by Branly76** [comment]
Ok
